### PR TITLE
fixes #31: deduction for lhs expression

### LINKED ISSUE #31: Failed to parse `(1+2)++`

### PR DESCRIPTION
**Pull request by ikarienator**
fixes #31

### CODE REVIEW

**Comment by michaelficarra** [comment]
Let's avoid using a pair. Wrap instead with

```js
class LHSIndicator {
  constructor(expression, isLeftHandSide) {
    this.expression = expression;
    this.isLeftHandSide = isLeftHandSide;
  }
}

**Comment by ikarienator** [comment]
Hmm, I think it's a good time to decide how to put the two branches together now.

**Comment by ikarienator** [comment]
I think we can commit this and rebase then revert this in es6 branch.

**Comment by ikarienator** [comment]
@michaelficarra Rebased. Please merge this.

**Pull request merged**
