### PR TITLE
fixes #304: validate exponentiation expression LHSs

### LINKED ISSUE #304: LHS of exponentiation expression parsed with incorrect precedence
``` js
-a ** b
```

parses successfully. I have no idea how this was allowed to happen.

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #304.

We should open a PR to test262-parser-tests adding these tests.

### CODE REVIEW

**Comment by bakkot** [comment]
This rejects `(-a) ** b`, which should also be added as a test.

**Comment by bakkot** [comment]
Because `() => a ** b` parses as `() => (a ** b)`, I'm pretty sure you can get away with storing the first token of the LHS, and only throwing if the first token was not `(`. But it's kind of a hack.

**Comment by michaelficarra** [comment]
Oh yeah. Whoops.

**Comment by bakkot** [comment]
Fixed and added test.

**Pull request merged**
