### PR TITLE
fixes #31: grouped expressions should be considered LeftHandSideExpression

### LINKED ISSUE #31: Failed to parse `(1+2)++`

### PR DESCRIPTION
**Pull request by ikarienator**
It was handled in AssignmentExpression but not in PostfixeExpression.

Fixes #31.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Nice. Can you add similar tests for `PrefixExpression` (unparenthesised)?

**Comment by ikarienator** [comment]
is `!!a` enough?

**Comment by michaelficarra** [comment]
No, I specifically care about leading `+` and `-`. I would like to see `++++a`, `++ +a`, `+ ++a`, and `+ +a` generated. Same thing for the `-` equivalents.

**Comment by ikarienator** [comment]
Let's merge this first and open an issue in the codegen.

**Comment by ikarienator** [comment]
Wow, they don't actually work. Let fix them altogether.

**Comment by ikarienator** [comment]
Ouch. The algorithm is wrong. It parses `(1) + (2) = 3`.

**Pull request closed without merging**
