### PR TITLE
test against io.js in CI

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by michaelficarra** [comment]
@ikarienator I can't figure out how this is happening. Can you investigate?

**Comment by michaelficarra** [comment]
Might have something to do with https://people.mozilla.org/~jorendorff/es6-draft.html#sec-escaperegexppattern

> The code points / or any LineTerminator occurring in the pattern shall be escaped in S as necessary to ensure that the String value formed by concatenating the Strings "/", S, "/", and F can be parsed (in an appropriate lexical context) as a RegularExpressionLiteral that behaves identically to the constructed regular expression.

I guess V8 started to conform to this recently.

**Comment by ikarienator** [comment]
That is because we are using `testEsprimaEquiv` to test regex's and the way to string. It doesn't pass my `npm test` either.

```
node --version
v1.1.0
```

**Comment by ikarienator** [comment]
The versions in travis we are using are too old.

**Pull request merged**
