### PR TITLE
fixes #93: allow ExpressionStatements starting with `let`

### LINKED ISSUE #93: ES6: `let()` is a valid CallExpression in ES6
Lookahead of ExpressionStatement is of two symbols `let [`.

Effecting https://people.mozilla.org/~jorendorff/es6-draft.html#sec-expression-statement and https://people.mozilla.org/~jorendorff/es6-draft.html#sec-iteration-statements.

### PR DESCRIPTION
**Pull request by ikarienator**
Fixes #93.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Backtracking, really?

**Comment by ikarienator** [comment]
No, it is only used for lookahead 2 tokens, so it's constant time and
doesn't change the time complexity.

**Comment by michaelficarra** [comment]
Add tests for saving/restoring lexer state, then :shipit:.

**Comment by ikarienator** [comment]
I can do it, but it's private, why?

**Comment by michaelficarra** [comment]
I guess it's private for now. Merging.

**Pull request merged**
