### PR TITLE
Keep track of cover grammars.

### LINKED ISSUE #112: `[x, ...y,] = 0` should fail
According to https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment, elision is not allowed after rest element.

Same for binding patterns.

### PR DESCRIPTION
**Pull request by ikarienator**
Close #112

### CODE REVIEW

**Comment by michaelficarra** [comment]
Build fails with failing tests.

**Comment by ikarienator** [comment]
@michaelficarra Finished refactor.

**Comment by michaelficarra** [comment]
Can you rebase? Does this allow duplicate `__proto__` in object destructuring in assignment position? We need to add a test for that.

**Comment by ikarienator** [comment]
Done.

**Pull request merged**
